"""phase 4 opportunities

Revision ID: 55fe0bc1b7ef
Revises: 0002_phase3
Create Date: 2026-09-03 05:29:05.926910
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.base


revision: str = '0003_phase4'
down_revision: str | None = '0002_phase3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_conditions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('measurable', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_conditions_kind'), 'opportunity_conditions', ['kind'], unique=False)
    op.create_index(op.f('ix_opportunity_conditions_opportunity_id'), 'opportunity_conditions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_conditions_state'), 'opportunity_conditions', ['state'], unique=False)
    op.create_table('opportunity_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interest', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score_at_decision', sa.Float(), nullable=False),
    sa.Column('confidence_at_decision', sa.Float(), nullable=False),
    sa.Column('risk_at_decision', sa.String(length=20), nullable=False),
    sa.Column('relevance_at_decision', sa.Float(), nullable=True),
    sa.Column('state_at_decision', sa.String(length=30), nullable=False),
    sa.Column('algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_decisions_decided_at'), 'opportunity_decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_opportunity_decisions_interest'), 'opportunity_decisions', ['interest'], unique=False)
    op.create_index(op.f('ix_opportunity_decisions_opportunity_id'), 'opportunity_decisions', ['opportunity_id'], unique=False)
    op.create_table('opportunity_participation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('capital_hint', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_participation_opportunity_id'), 'opportunity_participation', ['opportunity_id'], unique=False)
    op.create_table('opportunity_topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'topic_id', name='ux_opportunity_topic')
    )
    op.create_index(op.f('ix_opportunity_topics_opportunity_id'), 'opportunity_topics', ['opportunity_id'], unique=False)
    op.create_table('opportunity_trends',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('trend_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'trend_id', name='ux_opportunity_trend')
    )
    op.create_index(op.f('ix_opportunity_trends_opportunity_id'), 'opportunity_trends', ['opportunity_id'], unique=False)
    op.add_column('opportunities', sa.Column('opportunity_type', sa.String(length=30), nullable=False, server_default='business'))
    op.add_column('opportunities', sa.Column('state', sa.String(length=30), nullable=False, server_default='candidate'))
    op.add_column('opportunities', sa.Column('validation_status', sa.String(length=20), nullable=False, server_default='demo'))
    op.add_column('opportunities', sa.Column('country', sa.String(length=8), nullable=True))
    op.add_column('opportunities', sa.Column('industry', sa.String(length=60), nullable=True))
    op.add_column('opportunities', sa.Column('opportunity_score', sa.Float(), nullable=False, server_default='0'))
    op.add_column('opportunities', sa.Column('raw_score', sa.Float(), nullable=False, server_default='0'))
    op.add_column('opportunities', sa.Column('penalty_total', sa.Float(), nullable=False, server_default='0'))
    op.add_column('opportunities', sa.Column('personal_relevance', sa.Float(), nullable=True))
    op.add_column('opportunities', sa.Column('components', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('opportunities', sa.Column('penalties', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('opportunities', sa.Column('confidence_parts', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('opportunities', sa.Column('relevance_parts', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('opportunities', sa.Column('metrics', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('opportunities', sa.Column('warnings', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('opportunities', sa.Column('geographic_gap', sa.Float(), nullable=True))
    op.add_column('opportunities', sa.Column('geographic_gap_parts', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('opportunities', sa.Column('adoption_attention_ratio', sa.Float(), nullable=True))
    op.add_column('opportunities', sa.Column('adoption_attention_parts', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('opportunities', sa.Column('thesis', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('counter_thesis', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('mechanism', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('why_early', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('opportunities', sa.Column('missing_evidence', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('opportunities', sa.Column('next_research_steps', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('opportunities', sa.Column('analysis', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('opportunities', sa.Column('independent_source_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('opportunities', sa.Column('distinct_signal_types', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('opportunities', sa.Column('evidence_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('opportunities', sa.Column('algorithm_version', sa.String(length=20), nullable=False, server_default='0.0.0'))
    op.add_column('opportunities', sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('opportunities', sa.Column('peak_score', sa.Float(), nullable=False, server_default='0'))
    op.add_column('opportunities', sa.Column('primary_trend_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_opportunities_country'), 'opportunities', ['country'], unique=False)
    op.create_index(op.f('ix_opportunities_industry'), 'opportunities', ['industry'], unique=False)
    op.create_index(op.f('ix_opportunities_last_evaluated_at'), 'opportunities', ['last_evaluated_at'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_score'), 'opportunities', ['opportunity_score'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_type'), 'opportunities', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_opportunities_personal_relevance'), 'opportunities', ['personal_relevance'], unique=False)
    op.create_index(op.f('ix_opportunities_primary_trend_id'), 'opportunities', ['primary_trend_id'], unique=False)
    op.create_index(op.f('ix_opportunities_state'), 'opportunities', ['state'], unique=False)
    op.create_index(op.f('ix_opportunities_validation_status'), 'opportunities', ['validation_status'], unique=False)
    op.create_unique_constraint('ux_opportunity_subject', 'opportunities', ['opportunity_type', 'primary_trend_id', 'geo_scope'])
    # Named explicitly: an anonymous constraint cannot be dropped again, which is
    # what breaks an autogenerated downgrade.
    op.create_foreign_key(
        'fk_opportunities_primary_trend', 'opportunities', 'trends',
        ['primary_trend_id'], ['id'], ondelete='CASCADE',
    )
    op.add_column('opportunity_risks', sa.Column('confidence', sa.Float(), nullable=False, server_default='0'))
    op.add_column('opportunity_risks', sa.Column('mitigation', sa.Text(), nullable=True))
    op.add_column('opportunity_risks', sa.Column('is_blocking', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_opportunity_risks_category'), 'opportunity_risks', ['category'], unique=False)
    op.create_index(op.f('ix_opportunity_risks_severity'), 'opportunity_risks', ['severity'], unique=False)
    op.add_column('skeptic_reviews', sa.Column('strongest_counterargument', sa.Text(), nullable=True))
    op.add_column('skeptic_reviews', sa.Column('too_late_reasons', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('skeptic_reviews', sa.Column('inaccessible_reasons', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('skeptic_reviews', sa.Column('questions_asked', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('skeptic_reviews', sa.Column('prompt_version', sa.String(length=20), nullable=False, server_default='0.0.0'))
    op.add_column('skeptic_reviews', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_preferences', sa.Column('type_priority', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('user_preferences', sa.Column('priority_geographies', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('user_preferences', sa.Column('experience_industries', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('user_preferences', sa.Column('has_supplier_access', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user_preferences', sa.Column('has_distribution_access', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user_preferences', sa.Column('technical_ability', sa.String(length=20), nullable=False, server_default='medium'))
    op.add_column('user_preferences', sa.Column('weekly_hours_available', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('regulatory_access', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'regulatory_access')
    op.drop_column('user_preferences', 'weekly_hours_available')
    op.drop_column('user_preferences', 'technical_ability')
    op.drop_column('user_preferences', 'has_distribution_access')
    op.drop_column('user_preferences', 'has_supplier_access')
    op.drop_column('user_preferences', 'experience_industries')
    op.drop_column('user_preferences', 'priority_geographies')
    op.drop_column('user_preferences', 'type_priority')
    op.drop_column('skeptic_reviews', 'reviewed_at')
    op.drop_column('skeptic_reviews', 'prompt_version')
    op.drop_column('skeptic_reviews', 'questions_asked')
    op.drop_column('skeptic_reviews', 'inaccessible_reasons')
    op.drop_column('skeptic_reviews', 'too_late_reasons')
    op.drop_column('skeptic_reviews', 'strongest_counterargument')
    op.drop_index(op.f('ix_opportunity_risks_severity'), table_name='opportunity_risks')
    op.drop_index(op.f('ix_opportunity_risks_category'), table_name='opportunity_risks')
    op.drop_column('opportunity_risks', 'is_blocking')
    op.drop_column('opportunity_risks', 'mitigation')
    op.drop_column('opportunity_risks', 'confidence')
    op.drop_constraint('fk_opportunities_primary_trend', 'opportunities', type_='foreignkey')
    op.drop_constraint('ux_opportunity_subject', 'opportunities', type_='unique')
    op.drop_index(op.f('ix_opportunities_validation_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_state'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_primary_trend_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_personal_relevance'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_last_evaluated_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_industry'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_country'), table_name='opportunities')
    op.drop_column('opportunities', 'primary_trend_id')
    op.drop_column('opportunities', 'peak_score')
    op.drop_column('opportunities', 'last_evaluated_at')
    op.drop_column('opportunities', 'algorithm_version')
    op.drop_column('opportunities', 'evidence_count')
    op.drop_column('opportunities', 'distinct_signal_types')
    op.drop_column('opportunities', 'independent_source_count')
    op.drop_column('opportunities', 'analysis')
    op.drop_column('opportunities', 'next_research_steps')
    op.drop_column('opportunities', 'missing_evidence')
    op.drop_column('opportunities', 'why_early')
    op.drop_column('opportunities', 'mechanism')
    op.drop_column('opportunities', 'counter_thesis')
    op.drop_column('opportunities', 'thesis')
    op.drop_column('opportunities', 'adoption_attention_parts')
    op.drop_column('opportunities', 'adoption_attention_ratio')
    op.drop_column('opportunities', 'geographic_gap_parts')
    op.drop_column('opportunities', 'geographic_gap')
    op.drop_column('opportunities', 'warnings')
    op.drop_column('opportunities', 'metrics')
    op.drop_column('opportunities', 'relevance_parts')
    op.drop_column('opportunities', 'confidence_parts')
    op.drop_column('opportunities', 'penalties')
    op.drop_column('opportunities', 'components')
    op.drop_column('opportunities', 'personal_relevance')
    op.drop_column('opportunities', 'penalty_total')
    op.drop_column('opportunities', 'raw_score')
    op.drop_column('opportunities', 'opportunity_score')
    op.drop_column('opportunities', 'industry')
    op.drop_column('opportunities', 'country')
    op.drop_column('opportunities', 'validation_status')
    op.drop_column('opportunities', 'state')
    op.drop_column('opportunities', 'opportunity_type')
    op.drop_index(op.f('ix_opportunity_trends_opportunity_id'), table_name='opportunity_trends')
    op.drop_table('opportunity_trends')
    op.drop_index(op.f('ix_opportunity_topics_opportunity_id'), table_name='opportunity_topics')
    op.drop_table('opportunity_topics')
    op.drop_index(op.f('ix_opportunity_participation_opportunity_id'), table_name='opportunity_participation')
    op.drop_table('opportunity_participation')
    op.drop_index(op.f('ix_opportunity_decisions_opportunity_id'), table_name='opportunity_decisions')
    op.drop_index(op.f('ix_opportunity_decisions_interest'), table_name='opportunity_decisions')
    op.drop_index(op.f('ix_opportunity_decisions_decided_at'), table_name='opportunity_decisions')
    op.drop_table('opportunity_decisions')
    op.drop_index(op.f('ix_opportunity_conditions_state'), table_name='opportunity_conditions')
    op.drop_index(op.f('ix_opportunity_conditions_opportunity_id'), table_name='opportunity_conditions')
    op.drop_index(op.f('ix_opportunity_conditions_kind'), table_name='opportunity_conditions')
    op.drop_table('opportunity_conditions')
    # ### end Alembic commands ###
