"""phase 5 global platform

Revision ID: f6866e3e5d1e
Revises: 0003_phase4
Create Date: 2026-09-03 09:39:46.275420
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.base


revision: str = '0004_phase5'
down_revision: str | None = '0003_phase4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_adoption',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_key', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('adoption_growth', sa.Float(), nullable=True),
    sa.Column('attention_growth', sa.Float(), nullable=True),
    sa.Column('supplier_count', sa.Integer(), nullable=True),
    sa.Column('competitor_count', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=3), nullable=True),
    sa.Column('first_observed_days_ago', sa.Integer(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_key', 'country_code', name='ux_country_adoption')
    )
    op.create_index(op.f('ix_country_adoption_country_code'), 'country_adoption', ['country_code'], unique=False)
    op.create_index(op.f('ix_country_adoption_status'), 'country_adoption', ['status'], unique=False)
    op.create_index(op.f('ix_country_adoption_subject_key'), 'country_adoption', ['subject_key'], unique=False)
    op.create_table('country_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('data_coverage', sa.Float(), nullable=False),
    sa.Column('coverage_parts', sa.JSON(), nullable=False),
    sa.Column('last_coverage_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_profiles_data_coverage'), 'country_profiles', ['data_coverage'], unique=False)
    op.create_index(op.f('ix_country_profiles_iso_code'), 'country_profiles', ['iso_code'], unique=True)
    op.create_index(op.f('ix_country_profiles_region'), 'country_profiles', ['region'], unique=False)
    op.create_table('fx_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'as_of', name='ux_fx_rate')
    )
    op.create_index(op.f('ix_fx_rates_as_of'), 'fx_rates', ['as_of'], unique=False)
    op.create_index(op.f('ix_fx_rates_base_currency'), 'fx_rates', ['base_currency'], unique=False)
    op.create_index(op.f('ix_fx_rates_quote_currency'), 'fx_rates', ['quote_currency'], unique=False)
    op.create_table('country_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'key', 'as_of', name='ux_country_fact')
    )
    op.create_index(op.f('ix_country_facts_as_of'), 'country_facts', ['as_of'], unique=False)
    op.create_index(op.f('ix_country_facts_country_id'), 'country_facts', ['country_id'], unique=False)
    op.create_index(op.f('ix_country_facts_key'), 'country_facts', ['key'], unique=False)
    op.create_index(op.f('ix_country_facts_status'), 'country_facts', ['status'], unique=False)
    op.create_table('digests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digests_generated_at'), 'digests', ['generated_at'], unique=False)
    op.create_index(op.f('ix_digests_user_id'), 'digests', ['user_id'], unique=False)
    op.create_table('notification_channel_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('link_code', sa.String(length=64), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_id', name='ux_channel_external')
    )
    op.create_index(op.f('ix_notification_channel_links_channel'), 'notification_channel_links', ['channel'], unique=False)
    op.create_index(op.f('ix_notification_channel_links_external_id'), 'notification_channel_links', ['external_id'], unique=False)
    op.create_index(op.f('ix_notification_channel_links_link_code'), 'notification_channel_links', ['link_code'], unique=False)
    op.create_index(op.f('ix_notification_channel_links_user_id'), 'notification_channel_links', ['user_id'], unique=False)
    op.create_table('opportunity_change_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('old_value', sa.String(length=120), nullable=True),
    sa.Column('new_value', sa.String(length=120), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_change_events_kind'), 'opportunity_change_events', ['kind'], unique=False)
    op.create_index(op.f('ix_opportunity_change_events_occurred_at'), 'opportunity_change_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_opportunity_change_events_opportunity_id'), 'opportunity_change_events', ['opportunity_id'], unique=False)
    op.create_table('source_validations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checks_passed', sa.Integer(), nullable=False),
    sa.Column('checks_failed', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_validations_source_id'), 'source_validations', ['source_id'], unique=True)
    op.create_index(op.f('ix_source_validations_state'), 'source_validations', ['state'], unique=False)
    op.create_table('user_opportunity_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('feedback', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_opportunity_feedback_feedback'), 'user_opportunity_feedback', ['feedback'], unique=False)
    op.create_index(op.f('ix_user_opportunity_feedback_opportunity_id'), 'user_opportunity_feedback', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_user_opportunity_feedback_user_id'), 'user_opportunity_feedback', ['user_id'], unique=False)
    op.create_table('user_opportunity_relevance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('parts', sa.JSON(), nullable=False),
    sa.Column('path_relevance', sa.JSON(), nullable=False),
    sa.Column('best_path', sa.String(length=40), nullable=True),
    sa.Column('outside_profile', sa.Boolean(), nullable=False),
    sa.Column('formula_version', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='ux_user_opportunity_relevance')
    )
    op.create_index(op.f('ix_user_opportunity_relevance_opportunity_id'), 'user_opportunity_relevance', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_user_opportunity_relevance_relevance'), 'user_opportunity_relevance', ['relevance'], unique=False)
    op.create_index(op.f('ix_user_opportunity_relevance_user_id'), 'user_opportunity_relevance', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('home_country', sa.String(length=2), nullable=True),
    sa.Column('residence_country', sa.String(length=2), nullable=True),
    sa.Column('operating_countries', sa.JSON(), nullable=False),
    sa.Column('familiar_countries', sa.JSON(), nullable=False),
    sa.Column('target_countries', sa.JSON(), nullable=False),
    sa.Column('excluded_countries', sa.JSON(), nullable=False),
    sa.Column('interest_ranking', sa.JSON(), nullable=False),
    sa.Column('disabled_categories', sa.JSON(), nullable=False),
    sa.Column('industries', sa.JSON(), nullable=False),
    sa.Column('excluded_industries', sa.JSON(), nullable=False),
    sa.Column('capital_currency', sa.String(length=3), nullable=False),
    sa.Column('preferred_investment_amount', sa.Float(), nullable=True),
    sa.Column('max_capital', sa.Float(), nullable=True),
    sa.Column('capital_flexibility', sa.String(length=20), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('experience_industries', sa.JSON(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=False),
    sa.Column('time_horizon', sa.String(length=20), nullable=False),
    sa.Column('time_commitment', sa.String(length=20), nullable=False),
    sa.Column('display_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('min_global_score', sa.Float(), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('max_risk_level', sa.String(length=20), nullable=False),
    sa.Column('max_capital_required', sa.Float(), nullable=True),
    sa.Column('show_outside_profile', sa.Boolean(), nullable=False),
    sa.Column('digest_frequency', sa.String(length=20), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_home_country'), 'user_profiles', ['home_country'], unique=False)
    op.create_index(op.f('ix_user_profiles_residence_country'), 'user_profiles', ['residence_country'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('alert_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('trigger', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Uuid(), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_trigger'), 'alert_rules', ['trigger'], unique=False)
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_table('condition_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('condition_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('previous_state', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['opportunity_conditions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_checks_checked_at'), 'condition_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_condition_checks_condition_id'), 'condition_checks', ['condition_id'], unique=False)
    op.create_index(op.f('ix_condition_checks_state'), 'condition_checks', ['state'], unique=False)
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('opportunity_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('suppressed_reason', sa.String(length=200), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['opportunity_change_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedupe_key', name='ux_alert_dedupe')
    )
    op.create_index(op.f('ix_alert_deliveries_channel'), 'alert_deliveries', ['channel'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_dedupe_key'), 'alert_deliveries', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_status'), 'alert_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_user_id'), 'alert_deliveries', ['user_id'], unique=False)
    op.add_column('opportunities', sa.Column('evidence_countries', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('opportunities', sa.Column('transferability', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('watchlist_items', sa.Column('trend_id', sa.Uuid(), nullable=True))
    op.add_column('watchlist_items', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('watchlist_items', sa.Column('industry', sa.String(length=80), nullable=True))
    op.add_column('watchlist_items', sa.Column('label', sa.String(length=240), nullable=True))
    op.create_index(op.f('ix_watchlist_items_country_code'), 'watchlist_items', ['country_code'], unique=False)
    op.create_index(op.f('ix_watchlist_items_industry'), 'watchlist_items', ['industry'], unique=False)
    op.create_index(op.f('ix_watchlist_items_item_type'), 'watchlist_items', ['item_type'], unique=False)
    op.create_foreign_key('fk_watchlist_items_trend', 'watchlist_items', 'trends', ['trend_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_watchlist_items_trend', 'watchlist_items', type_='foreignkey')
    op.drop_index(op.f('ix_watchlist_items_item_type'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_industry'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_country_code'), table_name='watchlist_items')
    op.drop_column('watchlist_items', 'label')
    op.drop_column('watchlist_items', 'industry')
    op.drop_column('watchlist_items', 'country_code')
    op.drop_column('watchlist_items', 'trend_id')
    op.drop_column('opportunities', 'transferability')
    op.drop_column('opportunities', 'evidence_countries')
    op.drop_index(op.f('ix_alert_deliveries_user_id'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_status'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_dedupe_key'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_channel'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_index(op.f('ix_condition_checks_state'), table_name='condition_checks')
    op.drop_index(op.f('ix_condition_checks_condition_id'), table_name='condition_checks')
    op.drop_index(op.f('ix_condition_checks_checked_at'), table_name='condition_checks')
    op.drop_table('condition_checks')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_trigger'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_residence_country'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_home_country'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_opportunity_relevance_user_id'), table_name='user_opportunity_relevance')
    op.drop_index(op.f('ix_user_opportunity_relevance_relevance'), table_name='user_opportunity_relevance')
    op.drop_index(op.f('ix_user_opportunity_relevance_opportunity_id'), table_name='user_opportunity_relevance')
    op.drop_table('user_opportunity_relevance')
    op.drop_index(op.f('ix_user_opportunity_feedback_user_id'), table_name='user_opportunity_feedback')
    op.drop_index(op.f('ix_user_opportunity_feedback_opportunity_id'), table_name='user_opportunity_feedback')
    op.drop_index(op.f('ix_user_opportunity_feedback_feedback'), table_name='user_opportunity_feedback')
    op.drop_table('user_opportunity_feedback')
    op.drop_index(op.f('ix_source_validations_state'), table_name='source_validations')
    op.drop_index(op.f('ix_source_validations_source_id'), table_name='source_validations')
    op.drop_table('source_validations')
    op.drop_index(op.f('ix_opportunity_change_events_opportunity_id'), table_name='opportunity_change_events')
    op.drop_index(op.f('ix_opportunity_change_events_occurred_at'), table_name='opportunity_change_events')
    op.drop_index(op.f('ix_opportunity_change_events_kind'), table_name='opportunity_change_events')
    op.drop_table('opportunity_change_events')
    op.drop_index(op.f('ix_notification_channel_links_user_id'), table_name='notification_channel_links')
    op.drop_index(op.f('ix_notification_channel_links_link_code'), table_name='notification_channel_links')
    op.drop_index(op.f('ix_notification_channel_links_external_id'), table_name='notification_channel_links')
    op.drop_index(op.f('ix_notification_channel_links_channel'), table_name='notification_channel_links')
    op.drop_table('notification_channel_links')
    op.drop_index(op.f('ix_digests_user_id'), table_name='digests')
    op.drop_index(op.f('ix_digests_generated_at'), table_name='digests')
    op.drop_table('digests')
    op.drop_index(op.f('ix_country_facts_status'), table_name='country_facts')
    op.drop_index(op.f('ix_country_facts_key'), table_name='country_facts')
    op.drop_index(op.f('ix_country_facts_country_id'), table_name='country_facts')
    op.drop_index(op.f('ix_country_facts_as_of'), table_name='country_facts')
    op.drop_table('country_facts')
    op.drop_index(op.f('ix_fx_rates_quote_currency'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_base_currency'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_as_of'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_index(op.f('ix_country_profiles_region'), table_name='country_profiles')
    op.drop_index(op.f('ix_country_profiles_iso_code'), table_name='country_profiles')
    op.drop_index(op.f('ix_country_profiles_data_coverage'), table_name='country_profiles')
    op.drop_table('country_profiles')
    op.drop_index(op.f('ix_country_adoption_subject_key'), table_name='country_adoption')
    op.drop_index(op.f('ix_country_adoption_status'), table_name='country_adoption')
    op.drop_index(op.f('ix_country_adoption_country_code'), table_name='country_adoption')
    op.drop_table('country_adoption')
    # ### end Alembic commands ###
